[package]
name = "window_switcher"
description = "A CLI that allows switching between windows in Hyprland"
version = "0.2.1"
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/crate/window_switcher"
repository = "https://github.com/H3rmt/WindowSwitcher/"
keywords = ["hyprland", "hyprland"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "^4.4.11", features = ["derive"] }
hyprland = "=0.3.11"

[dev-dependencies]
random_color = "0.8.0"
svg = "0.14.0"

[features]
gui = ["gtk4", "gtk4-layer-shell"]