[package]
name = "window_switcher"
description = "A CLI app that allows switching between windows (of same class) in Hyprland"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
hyprland = "0.3.9"