[package]
name = "window_switcher"
description = "A CLI that allows switching between windows in Hyprland"
version = "0.2.1"
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/crate/window_switcher"
repository = "https://github.com/H3rmt/WindowSwitcher/"
keywords = ["hyprland", "hyprland"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "^4.4.11", features = ["derive"] }
hyprland = "=0.3.11"
gtk4 = { version = "0.7.3", optional = true }
libadwaita = { version = "0.5.3", optional = true }
gtk4-layer-shell = { version = "0.2.0", optional = true }
notify-rust = { version = "4.0.0", optional = true }
tokio = { version = "1.35.1", optional = true }
tokio-condvar = { version = "0.1.0", optional = true }
icon-loader = { version = "0.4.0", optional = true }

[dev-dependencies]
random_color = "0.8.0"
svg = "0.15.0"

[features]
default = ["gui", "daemon"]
gui = ["gtk4", "libadwaita", "gtk4-layer-shell", "tokio", "tokio-condvar", "icon-loader", "daemon"]
daemon = ["tokio"]
toast = ["notify-rust"]
