[package]
name = "hyprswitch"
description = "A CLI/GUI that allows switching between windows in Hyprland"
version = "1.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["h3rmt"]
documentation = "https://docs.rs/crate/hyprswitch"
repository = "https://github.com/h3rmt/hyprswitch/"
keywords = ["hyprland"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "^4.4.11", features = ["derive"] }
hyprland = { version = "0.3.13" }
tokio = { version = "1.35.1", features = ["full"] }
log = "0.4"
stderrlog = "0.6.0"
anyhow = "1.0.80"
lazy_static = "1.4.0"

gtk4 = { version = "0.7.3", optional = true }
#gtk4 = { version = "0.8.0", optional = true }
adw = { package = "libadwaita", version = "0.5.3", optional = true }
#adw = { package = "libadwaita", version = "0.6.0", optional = true }
gtk4-layer-shell = { version = "0.2.0", optional = true }
tokio-condvar = { version = "0.1.0", optional = true }

[dev-dependencies]
random_color = "0.8.0"
svg = "0.16.0"

[features]
default = ["gui"]
gui = ["gtk4", "gtk4-layer-shell", "tokio-condvar"]
libadwaita = ["adw", "gui"]

[profile.release]
strip = "debuginfo"
lto = true
opt-level = "s"
panic = "abort"
codegen-units = 1
