name: Publish

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if tag is -rc or -alpha and exit if it is
        run: |
          if [[ ${{ github.ref }} == *"-rc"* ]] || [[ ${{ github.ref }} == *"-alpha"* ]]; then
            echo "Skipping publish for ${{ github.ref }}"
            exit 0
          fi
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install gtk4-layer-shell
        run: sudo apt-get update
          && sudo apt -y install git libglib2.0-dev libgraphene-1.0-dev meson ninja-build libwayland-dev libgtk-4-dev gobject-introspection libadwaita-1-dev libgirepository1.0-dev python3 valac
          && git clone https://github.com/wmww/gtk4-layer-shell
          && cd gtk4-layer-shell
          && meson setup build
          && ninja -C build
          && sudo ninja -C build install
          && sudo ldconfig
      - run: cargo publish --all-features --token ${{ secrets.CRATES_TOKEN }}