on:
  push:
    tags:
      - '*'
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-publish
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-release
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_TYPES: tar.gz tar.xz tar.zst