name: Rust

on:
  push:
    branches: 
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-20.04, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    name: build ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v3
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: Load Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: rust-build-${{ matrix.platform }}
    - name: Build
      run: cargo build --verbose

  clippy:
    name: "Cargo clippy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-clippy
      - run: "rustup component add clippy"
      - uses: "actions-rs/cargo@v1"
        with:
          command: "clippy"
          args: "-- -D warnings"